#!/bin/sh

# add /Applications/TotalFinder.app in user's login items
osascript -e 'tell application "System Events"' -e 'make login item at beginning with properties {path:"/Applications/TotalFinder.app", kind:application}' -e 'end tell'

# tweak finder settings to play nice with TotalFinder
/usr/bin/defaults write com.apple.finder DisableAllAnimations -bool true
/usr/bin/defaults write com.apple.finder _FXShowPosixPathInTitle -bool false
/usr/bin/defaults write com.apple.finder AnimateWindowZoom -bool false
/usr/bin/defaults write com.apple.finder FXDisableFancyWindowTransition -bool true

sleep 2

# BRUTEFORCE: rename TotalFinder -> TotalFinder.bundle
# why? installer machinery stopped working for me strangely in 1.1.6, without any obvious reason
# reverted back to Packages 1.0.3 with the same issue...
#
# Some OS gods a protecting all *.bundle files under /Applications/TotalFinder.app
# I guess it is some interference with new MAS AI introduced in 10.6.6
# I saw they do some dirty Spotlight business to register apps with MAS App
rm -rf "/Applications/TotalFinder.app/Contents/Resources/TotalFinder.bundle"
mv "/Applications/TotalFinder.app/Contents/Resources/TotalFinder" "/Applications/TotalFinder.app/Contents/Resources/TotalFinder.bundle"

open "/Applications/TotalFinder.app"