#!/bin/sh

OLD_LAUNCH_DAEMON_PATH="/Library/LaunchDaemons/com.binaryage.echelon.launcher.plist"

# disable connection to echelon
killall -SIGUSR1 Finder
# give it some time
sleep 2
# unload extension
kextunload "/System/Library/Extensions/TotalFinder.kext"

# cleanup from previous version
launchctl unload -w "$OLD_LAUNCH_DAEMON_PATH"
rm "$OLD_LAUNCH_DAEMON_PATH"
kextunload "/System/Library/Extensions/echelon.kext"
rm -rf "/System/Library/Extensions/echelon.kext"

# echelon may not be available during first install, this is ok
exit 0