#!/bin/sh

osascript -e 'tell application "Finder" to quit'

# remove existing SIMBL installation (0.8.2 and earlier)
rm -rf "/Library/Application Support/SIMBL/Plugins/TotalFinder.bundle"

# BRUTEFORCE: remove existing installation in /Applications/TotalFinder.app
# why? installer machinery stopped working for me strangely in 1.1.6, without any obvious reason
# reverted back to Packages 1.0.3 with the same issue...
#
# Some OS gods a protecting all *.bundle files under /Applications/TotalFinder.app
# I guess it is some interference with new MAS AI introduced in 10.6.6
# I saw they do some dirty Spotlight business to register apps with MAS App
/usr/sbin/pkgutil --forget com.binaryage.pkg.totalfinder.app
rm -rf "/Applications/TotalFinder.app"

exit 0